// Command import-qt-theme writes tokens/tables_gen.go from the four colour
// tables in the Qt library's src/tokens/theme.cpp, so the Go tables stay
// exactly what the Qt ones are while both exist.
//
//	go run ./tools/import-qt-theme ~/kvit-ui/src/tokens/theme.cpp > tokens/tables_gen.go
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strings"
)

var (
	funcStart = regexp.MustCompile(`^Theme::Tokens (light|dark|sepia|highContrast)Tokens\(\)`)
	colorLine = regexp.MustCompile(`^\s+t\.([a-zA-Z]+) = QColor\("(#[0-9a-fA-F]{6})"\);`)
	rampStart = regexp.MustCompile(`^\s+t\.([a-zA-Z]+Ramp) = \{`)
	hexValue  = regexp.MustCompile(`"(#[0-9a-fA-F]{6})"`)
)

type table struct {
	colors map[string]string
	order  []string
	ramps  map[string][]string
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: import-qt-theme path/to/theme.cpp")
		os.Exit(2)
	}
	src, err := generate(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	os.Stdout.Write(src)
}

// generate returns the Go file for the Qt source at path.
func generate(path string) ([]byte, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	tables := map[string]*table{}
	var cur *table
	var ramp string
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if m := funcStart.FindStringSubmatch(line); m != nil {
			cur = &table{colors: map[string]string{}, ramps: map[string][]string{}}
			tables[m[1]] = cur
			continue
		}
		if cur == nil {
			continue
		}
		if strings.HasPrefix(line, "}") {
			cur, ramp = nil, ""
			continue
		}
		if ramp != "" {
			for _, m := range hexValue.FindAllStringSubmatch(line, -1) {
				cur.ramps[ramp] = append(cur.ramps[ramp], strings.ToLower(m[1]))
			}
			if strings.Contains(line, "};") {
				ramp = ""
			}
			continue
		}
		if m := colorLine.FindStringSubmatch(line); m != nil {
			cur.colors[m[1]] = strings.ToLower(m[2])
			cur.order = append(cur.order, m[1])
			continue
		}
		if m := rampStart.FindStringSubmatch(line); m != nil {
			ramp = m[1]
		}
	}
	names := []string{"light", "dark", "sepia", "highContrast"}
	for _, n := range names {
		if tables[n] == nil {
			return nil, fmt.Errorf("no %sTokens() table found", n)
		}
	}
	// Every table has to set the same tokens; a token one table forgot would
	// otherwise be the zero colour, black, in that theme.
	for _, n := range names[1:] {
		if a, b := keys(tables["light"].colors), keys(tables[n].colors); a != b {
			return nil, fmt.Errorf("the %s table sets different tokens from the light one:\n%s\n%s", n, a, b)
		}
	}
	var w bytes.Buffer
	fmt.Fprintln(&w, "// Code generated by tools/import-qt-theme from kvit-ui's src/tokens/theme.cpp. DO NOT EDIT.")
	fmt.Fprintln(&w)
	fmt.Fprintln(&w, "package tokens")
	fmt.Fprintln(&w)
	fmt.Fprintln(&w, `import "github.com/kvit-s/kvit-ui/palette"`)
	for _, n := range names {
		t := tables[n]
		fmt.Fprintf(&w, "\nvar %sTable = Tokens{\n", n)
		for _, k := range t.order {
			fmt.Fprintf(&w, "\t%s: palette.Hex(%q),\n", exported(k), t.colors[k])
		}
		for _, k := range []string{"categoricalRamp", "sequentialRamp", "divergingRamp"} {
			fmt.Fprintf(&w, "\t%s: []palette.Color{", exported(k))
			for i, h := range t.ramps[k] {
				if i > 0 {
					fmt.Fprint(&w, ", ")
				}
				fmt.Fprintf(&w, "palette.Hex(%q)", h)
			}
			fmt.Fprintln(&w, "},")
		}
		fmt.Fprintln(&w, "}")
	}
	// The names the tables set, so a test can check that every colour field of
	// Tokens has a value in every table.
	fmt.Fprint(&w, "\nvar qtTokenNames = []string{")
	for i, k := range tables["light"].order {
		if i > 0 {
			fmt.Fprint(&w, ", ")
		}
		fmt.Fprintf(&w, "%q", exported(k))
	}
	fmt.Fprintln(&w, "}")
	return format.Source(w.Bytes())
}

func exported(s string) string { return strings.ToUpper(s[:1]) + s[1:] }

func keys(m map[string]string) string {
	var k []string
	for x := range m {
		k = append(k, x)
	}
	sort.Strings(k)
	return strings.Join(k, " ")
}
