// Code generated by tools/gen-names from tokens.Tokens and tokens.Interface. DO NOT EDIT.

package kvitui

import (
	"github.com/kvit-s/kvit-ui/palette"
	"github.com/kvit-s/kvit-ui/tokens"
)

// One Ink for every colour of the theme, named after its token.
var (
	InkWindowBackground        Ink = func(t tokens.Tokens) palette.Color { return t.WindowBackground }
	InkPanelBackground         Ink = func(t tokens.Tokens) palette.Color { return t.PanelBackground }
	InkListBackground          Ink = func(t tokens.Tokens) palette.Color { return t.ListBackground }
	InkFooterBackground        Ink = func(t tokens.Tokens) palette.Color { return t.FooterBackground }
	InkPopupBackground         Ink = func(t tokens.Tokens) palette.Color { return t.PopupBackground }
	InkChipBackground          Ink = func(t tokens.Tokens) palette.Color { return t.ChipBackground }
	InkBannerBackground        Ink = func(t tokens.Tokens) palette.Color { return t.BannerBackground }
	InkCodePanelBackground     Ink = func(t tokens.Tokens) palette.Color { return t.CodePanelBackground }
	InkTextPrimary             Ink = func(t tokens.Tokens) palette.Color { return t.TextPrimary }
	InkTextSecondary           Ink = func(t tokens.Tokens) palette.Color { return t.TextSecondary }
	InkTextMuted               Ink = func(t tokens.Tokens) palette.Color { return t.TextMuted }
	InkTextFaint               Ink = func(t tokens.Tokens) palette.Color { return t.TextFaint }
	InkTextDisabled            Ink = func(t tokens.Tokens) palette.Color { return t.TextDisabled }
	InkBannerText              Ink = func(t tokens.Tokens) palette.Color { return t.BannerText }
	InkOnAccent                Ink = func(t tokens.Tokens) palette.Color { return t.OnAccent }
	InkBorder                  Ink = func(t tokens.Tokens) palette.Color { return t.Border }
	InkBorderStrong            Ink = func(t tokens.Tokens) palette.Color { return t.BorderStrong }
	InkQuoteBar                Ink = func(t tokens.Tokens) palette.Color { return t.QuoteBar }
	InkMutedGlyph              Ink = func(t tokens.Tokens) palette.Color { return t.MutedGlyph }
	InkHoverTint               Ink = func(t tokens.Tokens) palette.Color { return t.HoverTint }
	InkBlockHoverTint          Ink = func(t tokens.Tokens) palette.Color { return t.BlockHoverTint }
	InkFocusTint               Ink = func(t tokens.Tokens) palette.Color { return t.FocusTint }
	InkFocusRing               Ink = func(t tokens.Tokens) palette.Color { return t.FocusRing }
	InkSelectionTint           Ink = func(t tokens.Tokens) palette.Color { return t.SelectionTint }
	InkSelectionActiveTint     Ink = func(t tokens.Tokens) palette.Color { return t.SelectionActiveTint }
	InkBlockSelectionTint      Ink = func(t tokens.Tokens) palette.Color { return t.BlockSelectionTint }
	InkAccent                  Ink = func(t tokens.Tokens) palette.Color { return t.Accent }
	InkDanger                  Ink = func(t tokens.Tokens) palette.Color { return t.Danger }
	InkDangerBright            Ink = func(t tokens.Tokens) palette.Color { return t.DangerBright }
	InkSuccess                 Ink = func(t tokens.Tokens) palette.Color { return t.Success }
	InkWarning                 Ink = func(t tokens.Tokens) palette.Color { return t.Warning }
	InkPinColor                Ink = func(t tokens.Tokens) palette.Color { return t.PinColor }
	InkMarker                  Ink = func(t tokens.Tokens) palette.Color { return t.Marker }
	InkInlineCodeBackground    Ink = func(t tokens.Tokens) palette.Color { return t.InlineCodeBackground }
	InkHighlightBackground     Ink = func(t tokens.Tokens) palette.Color { return t.HighlightBackground }
	InkLink                    Ink = func(t tokens.Tokens) palette.Color { return t.Link }
	InkSearchMatchBackground   Ink = func(t tokens.Tokens) palette.Color { return t.SearchMatchBackground }
	InkSearchCurrentBackground Ink = func(t tokens.Tokens) palette.Color { return t.SearchCurrentBackground }
	InkChangedTextBackground   Ink = func(t tokens.Tokens) palette.Color { return t.ChangedTextBackground }
	InkAddedTextBackground     Ink = func(t tokens.Tokens) palette.Color { return t.AddedTextBackground }
	InkRemovedTextBackground   Ink = func(t tokens.Tokens) palette.Color { return t.RemovedTextBackground }
	InkCodeKeyword             Ink = func(t tokens.Tokens) palette.Color { return t.CodeKeyword }
	InkCodeType                Ink = func(t tokens.Tokens) palette.Color { return t.CodeType }
	InkCodeString              Ink = func(t tokens.Tokens) palette.Color { return t.CodeString }
	InkCodeComment             Ink = func(t tokens.Tokens) palette.Color { return t.CodeComment }
	InkCodeNumber              Ink = func(t tokens.Tokens) palette.Color { return t.CodeNumber }
	InkCalloutTip              Ink = func(t tokens.Tokens) palette.Color { return t.CalloutTip }
	InkAxisAttention           Ink = func(t tokens.Tokens) palette.Color { return t.AxisAttention }
	InkAxisAttentionText       Ink = func(t tokens.Tokens) palette.Color { return t.AxisAttentionText }
	InkAxisAgent               Ink = func(t tokens.Tokens) palette.Color { return t.AxisAgent }
	InkAxisAgentText           Ink = func(t tokens.Tokens) palette.Color { return t.AxisAgentText }
	InkScopeDiscovered         Ink = func(t tokens.Tokens) palette.Color { return t.ScopeDiscovered }
	InkSignalHard              Ink = func(t tokens.Tokens) palette.Color { return t.SignalHard }
	InkSignalSoft              Ink = func(t tokens.Tokens) palette.Color { return t.SignalSoft }
	InkSignalHygiene           Ink = func(t tokens.Tokens) palette.Color { return t.SignalHygiene }
	InkHatchAlt                Ink = func(t tokens.Tokens) palette.Color { return t.HatchAlt }
)

// One Measure for every value Interface derives from the interface size.
var (
	SizeBarHeight        Measure = (*tokens.Interface).BarHeight
	SizeBarHeightWide    Measure = (*tokens.Interface).BarHeightWide
	SizeBody             Measure = (*tokens.Interface).Body
	SizeBreadcrumbHeight Measure = (*tokens.Interface).BreadcrumbHeight
	SizeCaption          Measure = (*tokens.Interface).Caption
	SizeChipHeight       Measure = (*tokens.Interface).ChipHeight
	SizeColumnGap        Measure = (*tokens.Interface).ColumnGap
	SizeControlHeight    Measure = (*tokens.Interface).ControlHeight
	SizeDisplay          Measure = (*tokens.Interface).Display
	SizeFocusRingWidth   Measure = (*tokens.Interface).FocusRingWidth
	SizeHairline         Measure = (*tokens.Interface).Hairline
	SizeHeaderHeight     Measure = (*tokens.Interface).HeaderHeight
	SizeHeadline         Measure = (*tokens.Interface).Headline
	SizeHeightFloor      Measure = (*tokens.Interface).HeightFloor
	SizeIconSize         Measure = (*tokens.Interface).IconSize
	SizeIconSizeSmall    Measure = (*tokens.Interface).IconSizeSmall
	SizePaneWidth        Measure = (*tokens.Interface).PaneWidth
	SizePillHeight       Measure = (*tokens.Interface).PillHeight
	SizeRadiusBar        Measure = (*tokens.Interface).RadiusBar
	SizeRadiusCard       Measure = (*tokens.Interface).RadiusCard
	SizeRadiusChip       Measure = (*tokens.Interface).RadiusChip
	SizeRadiusControl    Measure = (*tokens.Interface).RadiusControl
	SizeRadiusPill       Measure = (*tokens.Interface).RadiusPill
	SizeRailWidth        Measure = (*tokens.Interface).RailWidth
	SizeRowHeight        Measure = (*tokens.Interface).RowHeight
	SizeRowHeightCompact Measure = (*tokens.Interface).RowHeightCompact
	SizeRowHeightSlim    Measure = (*tokens.Interface).RowHeightSlim
	SizeRowHeightSub     Measure = (*tokens.Interface).RowHeightSub
	SizeSidebarWidth     Measure = (*tokens.Interface).SidebarWidth
	SizeSmall            Measure = (*tokens.Interface).Small
	SizeSpace            Measure = (*tokens.Interface).Space
	SizeSpaceLoose       Measure = (*tokens.Interface).SpaceLoose
	SizeSpaceNear        Measure = (*tokens.Interface).SpaceNear
	SizeSpaceSnug        Measure = (*tokens.Interface).SpaceSnug
	SizeSpaceTight       Measure = (*tokens.Interface).SpaceTight
	SizeSpaceWide        Measure = (*tokens.Interface).SpaceWide
	SizeStackGap         Measure = (*tokens.Interface).StackGap
	SizeStatusBarHeight  Measure = (*tokens.Interface).StatusBarHeight
	SizeStrong           Measure = (*tokens.Interface).Strong
	SizeTabHeight        Measure = (*tokens.Interface).TabHeight
	SizeTagHeight        Measure = (*tokens.Interface).TagHeight
	SizeTitle            Measure = (*tokens.Interface).Title
	SizeViewMargin       Measure = (*tokens.Interface).ViewMargin
	SizeWidthDrawn       Measure = (*tokens.Interface).WidthDrawn
	SizeWidthFloor       Measure = (*tokens.Interface).WidthFloor
	SizeWidthLaptop      Measure = (*tokens.Interface).WidthLaptop
)
