// Command gen-names writes names_gen.go: one Ink for every colour of
// tokens.Tokens and one Measure for every value Interface derives from the
// interface size, so a component can be given a colour or a gap by name and
// keep following the theme and the size.
//
//	go run ./tools/gen-names > names_gen.go
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"reflect"

	"github.com/kvit-s/kvit-ui/palette"
	"github.com/kvit-s/kvit-ui/tokens"
)

func main() {
	src, err := generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	os.Stdout.Write(src)
}

func generate() ([]byte, error) {
	var w bytes.Buffer
	fmt.Fprintln(&w, "// Code generated by tools/gen-names from tokens.Tokens and tokens.Interface. DO NOT EDIT.")
	fmt.Fprintln(&w, "\npackage kvitui")
	fmt.Fprintln(&w, "\nimport (\n\t\"github.com/kvit-s/kvit-ui/palette\"\n\t\"github.com/kvit-s/kvit-ui/tokens\"\n)")
	fmt.Fprintln(&w, "\n// One Ink for every colour of the theme, named after its token.")
	fmt.Fprintln(&w, "var (")
	typ := reflect.TypeOf(tokens.Tokens{})
	colorType := reflect.TypeOf(palette.Color{})
	for i := 0; i < typ.NumField(); i++ {
		f := typ.Field(i)
		if f.Type != colorType {
			continue
		}
		fmt.Fprintf(&w, "Ink%s Ink = func(t tokens.Tokens) palette.Color { return t.%s }\n", f.Name, f.Name)
	}
	fmt.Fprintln(&w, ")")
	fmt.Fprintln(&w, "\n// One Measure for every value Interface derives from the interface size.")
	fmt.Fprintln(&w, "var (")
	it := reflect.TypeOf(&tokens.Interface{})
	intType := reflect.TypeOf(0)
	for i := 0; i < it.NumMethod(); i++ {
		m := it.Method(i)
		// Methods take the receiver as their first argument here.
		if m.Name == "FontSize" || m.Type.NumIn() != 1 || m.Type.NumOut() != 1 || m.Type.Out(0) != intType {
			continue
		}
		fmt.Fprintf(&w, "Size%s Measure = (*tokens.Interface).%s\n", m.Name, m.Name)
	}
	fmt.Fprintln(&w, ")")
	return format.Source(w.Bytes())
}
