// Command import-icons writes icons/catalog_gen.go from the icon catalogue
// source: every glyph the Phosphor font carries,
// by its Phosphor name, and the meaning names components are written in.
//
//	go run ./tools/import-icons path/to/iconcatalog.cpp > icons/catalog_gen.go
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"regexp"
)

var (
	glyphLine   = regexp.MustCompile(`^\s+\{ "([a-z0-9-]+)", 0x([0-9a-f]+) \},`)
	meaningLine = regexp.MustCompile(`^\s+\{ "([a-z0-9-]+)", "([a-z0-9-]+)" \},`)
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: import-icons path/to/iconcatalog.cpp")
		os.Exit(2)
	}
	src, err := generate(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	os.Stdout.Write(src)
}

// generate returns the Go file for the source at path.
func generate(path string) ([]byte, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	var glyphs, meanings [][2]string
	known := map[string]bool{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		if m := glyphLine.FindStringSubmatch(sc.Text()); m != nil {
			glyphs = append(glyphs, [2]string{m[1], m[2]})
			known[m[1]] = true
		} else if m := meaningLine.FindStringSubmatch(sc.Text()); m != nil {
			meanings = append(meanings, [2]string{m[1], m[2]})
		}
	}
	for _, m := range meanings {
		if !known[m[1]] {
			return nil, fmt.Errorf("the meaning %q draws %q, which the font does not have", m[0], m[1])
		}
	}
	var w bytes.Buffer
	fmt.Fprintln(&w, "// Code generated by tools/import-icons. DO NOT EDIT.")
	fmt.Fprintln(&w, "\npackage icons")
	fmt.Fprintln(&w, "\n// glyphs is every glyph the Phosphor font carries, by its Phosphor name.")
	fmt.Fprintln(&w, "var glyphs = map[string]rune{")
	for _, g := range glyphs {
		fmt.Fprintf(&w, "%q: 0x%s,\n", g[0], g[1])
	}
	fmt.Fprintln(&w, "}")
	fmt.Fprintln(&w, "\n// meanings maps what a symbol means to the Phosphor glyph that draws it, in")
	fmt.Fprintln(&w, "// the catalogue order.")
	fmt.Fprintln(&w, "var meanings = [][2]string{")
	for _, m := range meanings {
		fmt.Fprintf(&w, "{%q, %q},\n", m[0], m[1])
	}
	fmt.Fprintln(&w, "}")
	return format.Source(w.Bytes())
}
